# https://github.com/peaceiris/actions-gh-pages

name: github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  publish:

    name: Publish to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Get dependencies
        run: npm install

      - name: Build distribution files
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
